### ISSUE TITLE
step by step

### ISSUE THREAD

**Issue by jaimebayes** [ufkapano/graphs-dict#1]
Hi there,

I am studying your graph classes to obtain MST.

I would like to follow the result of some lines, usually I use the print function, but I am having troubles when the code is in classes, because I do not know how to make it print between lines.
I understand this could be very obvious for most of you, but I am not proficient on object oriented programming. 
Example: if I want to see how change min_edges I use:
>>....
>>min_edges = dict(((node, dummy_edge) for node in forest))
>>print min_edges
>>....

How can I see the content of this list or other variables? 
Any advice would be appreciated.

Thanks, Jaime

**Comment by ufkapano** [comment]
Hello Jaime,

"print" should work inside classes, you have to run the algorithm:

>>> from graphtheory.structures.edges import Edge
>>> from graphtheory.structures.graphs import Graph
>>> from graphtheory.spanningtrees.boruvka import BoruvkaMST
>>> G = Graph(n=10, False) # an exemplary undirected graph
# Add nodes and edges here.
>>> algorithm = BoruvkaMST(G)
>>> algorithm.run()     # here you will see results from your "print"

Regards,
Andrzej

--
dr hab. Andrzej Kapanowski
Sekretarz Wydzia�owej Komisji Rekrutacyjnej
Uniwersytet Jagiello�ski, Instytut Fizyki
30-348 Krak�w, �ojasiewicza 11
tel. (+48 12) 664 4628
e-mail: andrzej.kapanowski@uj.edu.pl


----- Original Message -----

**Comment by jaimebayes** [comment]
Hi Andrzej,

I try using Spyder environment (anaconda) and it works fine as you said. My problem was that I was running your code from jupyter notebook, but I could not made the print function work there. I dont know what could be the reason. But well, in the meantime, I will continue studying your MST codes from spyder.

Thanks for your soon answer, 
Jaime
