### ISSUE TITLE
Why not make `Dijkstra` a subclass of `DijkstraMatrix` 

### ISSUE THREAD

**Issue by kgashok** [ufkapano/graphs-dict#4]
After all, they do share a lot of code. 

I tried this on my own repo and the test cases did pass. 
https://github.com/kgashok/graphs-dict/commit/f93e6b109367c957bcdc1964499e6487ce104120

Should I do a PR?

**Comment by ufkapano** [comment]
Well, I agree that some code is repeated, but I don't want
to change it. It should be simple and readable as a pseudocode and as efficient as a theory says.
Thank you for your interest in my package.

Regards,

--
dr hab. Andrzej Kapanowski
Sekretarz Wydziałowego Zespołu Rekrutacyjnego
Uniwersytet Jagielloński, Instytut Fizyki
30-384 Kraków, Łojasiewicza 11
tel. +48 12 664 4628
email: andrzej.kapanowski@uj.edu.pl

________________________________
Od: Ashok Bakthavathsalam <notifications@github.com>
Wysłane: poniedziałek, 10 lutego 2020 15:21
Do: ufkapano/graphs-dict <graphs-dict@noreply.github.com>
DW: Subscribed <subscribed@noreply.github.com>
Temat: [ufkapano/graphs-dict] Why not make `Dijkstra` a subclass of `DijkstraMatrix` (#4)


After all, they do share a lot of code.

I tried this on my own repo and the test cases did pass.
kgashok@f93e6b1<https://github.com/kgashok/graphs-dict/commit/f93e6b109367c957bcdc1964499e6487ce104120>

Should I do a PR?
