### ISSUE TITLE
ASCII depiction of graph

### ISSUE THREAD

**Issue by kgashok** [ufkapano/graphs-dict#5]
Is there a way to display the graph in ASCII art? Similar to what [`binarytree`](https://github.com/joowani/binarytree/blob/master/README.rst#getting-started) does? 
Or what would you suggest is the best way to visualize the graph?

**Comment by ufkapano** [comment]
I haven't seen any tool to display a graph in ASCII art.
Maybe for planar graphs it is possible to create something
but it will be difficult.

--
dr hab. Andrzej Kapanowski
Sekretarz Wydziałowego Zespołu Rekrutacyjnego
Uniwersytet Jagielloński, Instytut Fizyki
30-384 Kraków, Łojasiewicza 11
tel. +48 12 664 4628
email: andrzej.kapanowski@uj.edu.pl

________________________________
Od: Ashok Bakthavathsalam <notifications@github.com>
Wysłane: poniedziałek, 10 lutego 2020 17:31
Do: ufkapano/graphs-dict <graphs-dict@noreply.github.com>
DW: Subscribed <subscribed@noreply.github.com>
Temat: [ufkapano/graphs-dict] ASCII depiction of graph (#5)


Is there a way to display the graph in ASCII art? Similar to what binarytree<https://github.com/joowani/binarytree/blob/master/README.rst#getting-started> does?

**Comment by ufkapano** [comment]
The graph structure can be described by a tree decomposition (a tree with bags) but finding a TD is a hard problem in general. I am going to add some heuristic algorithms for finding TD (or a chordal completion). You can check the ToTo website http://treedecompositions.com/
